[project]
name = "onecut"
version = "0.1.0"
description = "One cut - Edit your video by editing code."
readme = "README.md"
authors = [
    { name = "Siyuan Ma", email = "smy20011@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "faster-whisper>=1.2.1",
]

[project.scripts]
onecut = "onecut:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
